-- Migration: Add Egyptian Colloquial Arabic Rules
-- This adds rules requiring Arabic titles and descriptions to be in Egyptian Colloquial dialect

-- Add rule for title in Egyptian Colloquial Arabic
INSERT INTO ai_rules (rule_key, instruction, scope, priority, version, is_active, metadata)
VALUES
  ('title.egyptian_colloquial', 'CRITICAL: When generating content in Arabic, you MUST use Egyptian Colloquial Arabic (المصرية العامية). Do NOT use Modern Standard Arabic (الفصحى) or any other Arabic dialect. Use natural, conversational Egyptian Arabic that is commonly spoken in Egypt. Examples: use "عايز" instead of "يريد", "عندي" instead of "لدي", "إيه" instead of "ماذا", etc.', 'global', 2, 1, true, '{"category": "title", "type": "restriction", "language": "ar"}'::jsonb),
  ('title.egyptian_colloquial.ar', 'مهم جداً: عند توليد المحتوى بالعربية، يجب عليك استخدام اللهجة المصرية العامية حصراً. لا تستخدم العربية الفصحى أو أي لهجة عربية أخرى. استخدم العربية المصرية الطبيعية والمحادثة التي يتحدث بها المصريون عادة. أمثلة: استخدم "عايز" بدلاً من "يريد"، "عندي" بدلاً من "لدي"، "إيه" بدلاً من "ماذا"، إلخ.', 'global', 2, 1, true, '{"category": "title", "type": "restriction", "language": "ar"}'::jsonb),
  ('description.egyptian_colloquial', 'CRITICAL: When generating content in Arabic, you MUST use Egyptian Colloquial Arabic (المصرية العامية). Do NOT use Modern Standard Arabic (الفصحى) or any other Arabic dialect. Use natural, conversational Egyptian Arabic that is commonly spoken in Egypt. Examples: use "عايز" instead of "يريد", "عندي" instead of "لدي", "إيه" instead of "ماذا", "عشان" instead of "لأن", "في" instead of "يوجد", etc.', 'global', 2, 1, true, '{"category": "description", "type": "restriction", "language": "ar"}'::jsonb),
  ('description.egyptian_colloquial.ar', 'مهم جداً: عند توليد المحتوى بالعربية، يجب عليك استخدام اللهجة المصرية العامية حصراً. لا تستخدم العربية الفصحى أو أي لهجة عربية أخرى. استخدم العربية المصرية الطبيعية والمحادثة التي يتحدث بها المصريون عادة. أمثلة: استخدم "عايز" بدلاً من "يريد"، "عندي" بدلاً من "لدي"، "إيه" بدلاً من "ماذا"، "عشان" بدلاً من "لأن"، "في" بدلاً من "يوجد"، إلخ.', 'global', 2, 1, true, '{"category": "description", "type": "restriction", "language": "ar"}'::jsonb),
  ('title.avoid_ordering_slang', 'ABSOLUTELY FORBIDDEN: You MUST NEVER use ordering, commanding, or imperative verbs in Arabic titles. These words are STRICTLY PROHIBITED: "ساهم", "شارك", "شاركنا", "ساعد", "تبرع", "ادعم", "انضم", "ساعدنا", "ادعمنا", "تبرع الآن", "ساهم في", "شارك في", or any form of direct command. Instead of "شارك في عمار بيت الله" use descriptive language like "عمار بيت الله يحتاج مساعدتك" or "نحتاج مساعدتك في عمار بيت الله". Instead of "ساهم في افتتاح تجديد المسجد" use "تجديد المسجد يحتاج دعمك" or "افتتاح المسجد بعد التجديد يحتاج مساعدتك". Always use descriptive, inviting language that explains the situation rather than commanding action.', 'global', 1, 1, true, '{"category": "title", "type": "restriction", "language": "ar"}'::jsonb),
  ('title.avoid_ordering_slang.ar', 'ممنوع تماماً: لا تستخدم أبداً أفعال الأمر أو الأوامر المباشرة في العناوين العربية. هذه الكلمات ممنوعة تماماً: "ساهم"، "شارك"، "شاركنا"، "ساعد"، "تبرع"، "ادعم"، "انضم"، "ساعدنا"، "ادعمنا"، "تبرع الآن"، "ساهم في"، "شارك في"، أو أي شكل من أشكال الأمر المباشر. بدلاً من "شارك في عمار بيت الله" استخدم لغة وصفية مثل "عمار بيت الله يحتاج مساعدتك" أو "نحتاج مساعدتك في عمار بيت الله". بدلاً من "ساهم في افتتاح تجديد المسجد" استخدم "تجديد المسجد يحتاج دعمك" أو "افتتاح المسجد بعد التجديد يحتاج مساعدتك". استخدم دائماً لغة وصفية ودعوية تشرح الوضع بدلاً من أن تأمر بالعمل.', 'global', 1, 1, true, '{"category": "title", "type": "restriction", "language": "ar"}'::jsonb),
  ('description.avoid_ordering_slang', 'ABSOLUTELY FORBIDDEN: You MUST NEVER use ordering, commanding, or imperative verbs in Arabic descriptions. These words are STRICTLY PROHIBITED: "ساهم", "شارك", "شاركنا", "ساعد", "تبرع", "ادعم", "انضم", "ساعدنا", "ادعمنا", "تبرع الآن", "ساهم في", "شارك في", or any form of direct command. Instead of "شارك في عمار بيت الله" use descriptive language like "عمار بيت الله يحتاج مساعدتك" or "نحتاج مساعدتك في عمار بيت الله". Instead of "ساهم في افتتاح تجديد المسجد" use "تجديد المسجد يحتاج دعمك" or "افتتاح المسجد بعد التجديد يحتاج مساعدتك". Always use descriptive, inviting language that explains the situation rather than commanding action.', 'global', 1, 1, true, '{"category": "description", "type": "restriction", "language": "ar"}'::jsonb),
  ('description.avoid_ordering_slang.ar', 'ممنوع تماماً: لا تستخدم أبداً أفعال الأمر أو الأوامر المباشرة في الوصف العربي. هذه الكلمات ممنوعة تماماً: "ساهم"، "شارك"، "شاركنا"، "ساعد"، "تبرع"، "ادعم"، "انضم"، "ساعدنا"، "ادعمنا"، "تبرع الآن"، "ساهم في"، "شارك في"، أو أي شكل من أشكال الأمر المباشر. بدلاً من "شارك في عمار بيت الله" استخدم لغة وصفية مثل "عمار بيت الله يحتاج مساعدتك" أو "نحتاج مساعدتك في عمار بيت الله". بدلاً من "ساهم في افتتاح تجديد المسجد" استخدم "تجديد المسجد يحتاج دعمك" أو "افتتاح المسجد بعد التجديد يحتاج مساعدتك". استخدم دائماً لغة وصفية ودعوية تشرح الوضع بدلاً من أن تأمر بالعمل.', 'global', 1, 1, true, '{"category": "description", "type": "restriction", "language": "ar"}'::jsonb)
ON CONFLICT (rule_key) DO UPDATE SET
  instruction = EXCLUDED.instruction,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();

-- Comments
COMMENT ON TABLE ai_rules IS 'Core AI rules table. Rules are small, human-written instructions that are combined at runtime into AI system prompts. Rules are ordered by priority and filtered by scope.';

